version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/desktop"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/storybook"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/web"
    schedule:
      interval: "daily"